// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaCalificaciones.Data;

#nullable disable

namespace SistemaCalificaciones.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601135448_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnioEscolar", b =>
                {
                    b.Property<int>("IdAnioEscolar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnioEscolar"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Cerrado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAnioEscolar");

                    b.ToTable("AniosEscolares");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.ActividadEvaluativa", b =>
                {
                    b.Property<int>("IdActividadEvaluativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActividadEvaluativa"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAsignacionDocente")
                        .HasColumnType("int");

                    b.Property<int>("IdPeriodoPublicacion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdActividadEvaluativa");

                    b.HasIndex("IdAsignacionDocente");

                    b.HasIndex("IdPeriodoPublicacion");

                    b.ToTable("ActividadesEvaluativas");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.AsignacionDocente", b =>
                {
                    b.Property<int>("IdAsignacionDocente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsignacionDocente"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAnioEscolar")
                        .HasColumnType("int");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<int>("IdMaestro")
                        .HasColumnType("int");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int");

                    b.HasKey("IdAsignacionDocente");

                    b.HasIndex("IdAnioEscolar");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdMateria");

                    b.HasIndex("IdMaestro", "IdCurso", "IdMateria", "IdAnioEscolar")
                        .IsUnique();

                    b.ToTable("AsignacionesDocentes");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.CalificacionPeriodo", b =>
                {
                    b.Property<int>("IdCalificacionPeriodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCalificacionPeriodo"));

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAsignacionDocente")
                        .HasColumnType("int");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.Property<int>("IdPeriodoPublicacion")
                        .HasColumnType("int");

                    b.Property<decimal>("NotaFinal")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("Publicada")
                        .HasColumnType("bit");

                    b.HasKey("IdCalificacionPeriodo");

                    b.HasIndex("IdAsignacionDocente");

                    b.HasIndex("IdPeriodoPublicacion");

                    b.HasIndex("IdEstudiante", "IdAsignacionDocente", "IdPeriodoPublicacion")
                        .IsUnique();

                    b.ToTable("CalificacionesPeriodo");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Curso", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCurso"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("IdGrado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seccion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCurso");

                    b.HasIndex("IdGrado");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Estudiante", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstudiante"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstudiante");

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasFilter("[IdUsuario] IS NOT NULL");

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Grado", b =>
                {
                    b.Property<int>("IdGrado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrado"));

                    b.Property<int>("IdNivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("IdGrado");

                    b.HasIndex("IdNivel");

                    b.ToTable("Grados");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.GradoMateria", b =>
                {
                    b.Property<int>("IdGradoMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGradoMateria"));

                    b.Property<int>("IdGrado")
                        .HasColumnType("int");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int");

                    b.HasKey("IdGradoMateria");

                    b.HasIndex("IdMateria");

                    b.HasIndex("IdGrado", "IdMateria")
                        .IsUnique();

                    b.ToTable("GradoMaterias");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Inscripcion", b =>
                {
                    b.Property<int>("IdInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInscripcion"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAnioEscolar")
                        .HasColumnType("int");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.HasKey("IdInscripcion");

                    b.HasIndex("IdAnioEscolar");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdEstudiante", "IdAnioEscolar")
                        .IsUnique();

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Maestro", b =>
                {
                    b.Property<int>("IdMaestro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaestro"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoEmpleado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especialidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMaestro");

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasFilter("[IdUsuario] IS NOT NULL");

                    b.ToTable("Maestros");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Materia", b =>
                {
                    b.Property<int>("IdMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMateria"));

                    b.Property<string>("Abreviatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMateria");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Nivel", b =>
                {
                    b.Property<int>("IdNivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNivel"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNivel");

                    b.ToTable("Niveles");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.NotaActividad", b =>
                {
                    b.Property<int>("IdNotaActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotaActividad"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdActividadEvaluativa")
                        .HasColumnType("int");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.Property<decimal>("Nota")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdNotaActividad");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdActividadEvaluativa", "IdEstudiante")
                        .IsUnique();

                    b.ToTable("NotasActividades");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Observacion", b =>
                {
                    b.Property<int>("IdObservacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdObservacion"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAsignacionDocente")
                        .HasColumnType("int");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.Property<int>("IdPeriodoPublicacion")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdObservacion");

                    b.HasIndex("IdAsignacionDocente");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdPeriodoPublicacion");

                    b.ToTable("Observaciones");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Padre", b =>
                {
                    b.Property<int>("IdPadre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPadre"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("LugarTrabajo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoLaboral")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPadre");

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasFilter("[IdUsuario] IS NOT NULL");

                    b.ToTable("Padres");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.PadreEstudiante", b =>
                {
                    b.Property<int>("IdPadreEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPadreEstudiante"));

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.Property<int>("IdPadre")
                        .HasColumnType("int");

                    b.Property<string>("Parentesco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ResponsableAcademico")
                        .HasColumnType("bit");

                    b.HasKey("IdPadreEstudiante");

                    b.HasIndex("IdEstudiante");

                    b.HasIndex("IdPadre", "IdEstudiante")
                        .IsUnique();

                    b.ToTable("PadreEstudiantes");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.PeriodoPublicacion", b =>
                {
                    b.Property<int>("IdPeriodoPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPeriodoPublicacion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAnioEscolar")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPeriodoPublicacion");

                    b.HasIndex("IdAnioEscolar");

                    b.ToTable("PeriodosPublicacion");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            Nombre = "Maestro"
                        },
                        new
                        {
                            IdRol = 3,
                            Nombre = "Estudiante"
                        },
                        new
                        {
                            IdRol = 4,
                            Nombre = "Padre"
                        });
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("DebeCambiarPassword")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.ActividadEvaluativa", b =>
                {
                    b.HasOne("SistemaCalificaciones.Models.AsignacionDocente", "AsignacionDocente")
                        .WithMany("ActividadesEvaluativas")
                        .HasForeignKey("IdAsignacionDocente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCalificaciones.Models.PeriodoPublicacion", "PeriodoPublicacion")
                        .WithMany("ActividadesEvaluativas")
                        .HasForeignKey("IdPeriodoPublicacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AsignacionDocente");

                    b.Navigation("PeriodoPublicacion");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.AsignacionDocente", b =>
                {
                    b.HasOne("AnioEscolar", "AnioEscolar")
                        .WithMany()
                        .HasForeignKey("IdAnioEscolar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCalificaciones.Models.Curso", "Curso")
                        .WithMany("AsignacionesDocentes")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCalificaciones.Models.Maestro", "Maestro")
                        .WithMany("AsignacionesDocentes")
                        .HasForeignKey("IdMaestro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCalificaciones.Models.Materia", "Materia")
                        .WithMany("AsignacionesDocentes")
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnioEscolar");

                    b.Navigation("Curso");

                    b.Navigation("Maestro");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.CalificacionPeriodo", b =>
                {
                    b.HasOne("SistemaCalificaciones.Models.AsignacionDocente", "AsignacionDocente")
                        .WithMany("CalificacionesPeriodo")
                        .HasForeignKey("IdAsignacionDocente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCalificaciones.Models.Estudiante", "Estudiante")
                        .WithMany("CalificacionesPeriodo")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCalificaciones.Models.PeriodoPublicacion", "PeriodoPublicacion")
                        .WithMany("CalificacionesPeriodo")
                        .HasForeignKey("IdPeriodoPublicacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AsignacionDocente");

                    b.Navigation("Estudiante");

                    b.Navigation("PeriodoPublicacion");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Curso", b =>
                {
                    b.HasOne("SistemaCalificaciones.Models.Grado", "Grado")
                        .WithMany("Cursos")
                        .HasForeignKey("IdGrado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grado");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Estudiante", b =>
                {
                    b.HasOne("SistemaCalificaciones.Models.Usuario", "Usuario")
                        .WithOne("Estudiante")
                        .HasForeignKey("SistemaCalificaciones.Models.Estudiante", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Grado", b =>
                {
                    b.HasOne("SistemaCalificaciones.Models.Nivel", "Nivel")
                        .WithMany("Grados")
                        .HasForeignKey("IdNivel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.GradoMateria", b =>
                {
                    b.HasOne("SistemaCalificaciones.Models.Grado", "Grado")
                        .WithMany("GradoMaterias")
                        .HasForeignKey("IdGrado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCalificaciones.Models.Materia", "Materia")
                        .WithMany("GradoMaterias")
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grado");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Inscripcion", b =>
                {
                    b.HasOne("AnioEscolar", "AnioEscolar")
                        .WithMany("Inscripciones")
                        .HasForeignKey("IdAnioEscolar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCalificaciones.Models.Curso", "Curso")
                        .WithMany("Inscripciones")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCalificaciones.Models.Estudiante", "Estudiante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnioEscolar");

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Maestro", b =>
                {
                    b.HasOne("SistemaCalificaciones.Models.Usuario", "Usuario")
                        .WithOne("Maestro")
                        .HasForeignKey("SistemaCalificaciones.Models.Maestro", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.NotaActividad", b =>
                {
                    b.HasOne("SistemaCalificaciones.Models.ActividadEvaluativa", "ActividadEvaluativa")
                        .WithMany("NotasActividades")
                        .HasForeignKey("IdActividadEvaluativa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCalificaciones.Models.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActividadEvaluativa");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Observacion", b =>
                {
                    b.HasOne("SistemaCalificaciones.Models.AsignacionDocente", "AsignacionDocente")
                        .WithMany()
                        .HasForeignKey("IdAsignacionDocente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCalificaciones.Models.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCalificaciones.Models.PeriodoPublicacion", "PeriodoPublicacion")
                        .WithMany()
                        .HasForeignKey("IdPeriodoPublicacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AsignacionDocente");

                    b.Navigation("Estudiante");

                    b.Navigation("PeriodoPublicacion");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Padre", b =>
                {
                    b.HasOne("SistemaCalificaciones.Models.Usuario", "Usuario")
                        .WithOne("Padre")
                        .HasForeignKey("SistemaCalificaciones.Models.Padre", "IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.PadreEstudiante", b =>
                {
                    b.HasOne("SistemaCalificaciones.Models.Estudiante", "Estudiante")
                        .WithMany("PadreEstudiantes")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCalificaciones.Models.Padre", "Padre")
                        .WithMany("PadreEstudiantes")
                        .HasForeignKey("IdPadre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Padre");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.PeriodoPublicacion", b =>
                {
                    b.HasOne("AnioEscolar", "AnioEscolar")
                        .WithMany("PeriodosPublicacion")
                        .HasForeignKey("IdAnioEscolar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnioEscolar");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Usuario", b =>
                {
                    b.HasOne("SistemaCalificaciones.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AnioEscolar", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("PeriodosPublicacion");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.ActividadEvaluativa", b =>
                {
                    b.Navigation("NotasActividades");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.AsignacionDocente", b =>
                {
                    b.Navigation("ActividadesEvaluativas");

                    b.Navigation("CalificacionesPeriodo");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Curso", b =>
                {
                    b.Navigation("AsignacionesDocentes");

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Estudiante", b =>
                {
                    b.Navigation("CalificacionesPeriodo");

                    b.Navigation("Inscripciones");

                    b.Navigation("PadreEstudiantes");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Grado", b =>
                {
                    b.Navigation("Cursos");

                    b.Navigation("GradoMaterias");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Maestro", b =>
                {
                    b.Navigation("AsignacionesDocentes");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Materia", b =>
                {
                    b.Navigation("AsignacionesDocentes");

                    b.Navigation("GradoMaterias");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Nivel", b =>
                {
                    b.Navigation("Grados");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Padre", b =>
                {
                    b.Navigation("PadreEstudiantes");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.PeriodoPublicacion", b =>
                {
                    b.Navigation("ActividadesEvaluativas");

                    b.Navigation("CalificacionesPeriodo");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaCalificaciones.Models.Usuario", b =>
                {
                    b.Navigation("Estudiante");

                    b.Navigation("Maestro");

                    b.Navigation("Padre");
                });
#pragma warning restore 612, 618
        }
    }
}
